# Generated by Django 4.1.4 on 2023-02-04 11:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Empowerapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='jobapply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userjobpost', models.EmailField(max_length=254)),
                ('name', models.CharField(max_length=80)),
                ('email', models.EmailField(max_length=254)),
                ('mobile', models.BigIntegerField()),
                ('address', models.CharField(max_length=80)),
                ('city', models.CharField(max_length=80)),
                ('cv', models.FileField(upload_to='CV')),
            ],
        ),
        migrations.AlterField(
            model_name='adminlogin',
            name='created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 2, 4, 17, 12, 54, 647970)),
        ),
    ]
