# Generated by Django 4.1.4 on 2023-02-04 14:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Empowerapp', '0003_delete_jobapply_alter_adminlogin_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='jobapply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userjobpost', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=80)),
                ('email', models.EmailField(max_length=254)),
                ('mobile', models.BigIntegerField()),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=80)),
                ('cv', models.FileField(upload_to='CV')),
            ],
        ),
        migrations.AlterField(
            model_name='adminlogin',
            name='created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 2, 4, 20, 26, 35, 92460)),
        ),
    ]
